[package]
authors = ["duan <wddwyss@gmail.com>"]
edition = "2018"
name = "generate-random-point-in-a-circle"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
