[package]
name = "find-k-th-smallest-pair-distance"
version = "0.1.0"
authors = ["duan <wddwyss@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
