[package]
name = "number-of-restricted-paths-from-first-to-last-node"
version = "0.1.0"
authors = ["duan <wddwyss@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
